Communication with frontend
milkyway1170/my_favorite_movies_backend pull request #10
Opened 2022-05-05 14:30 UTC by milkyway1170

2022-05-11 08:13 UTC, reshetov approved these changes

2022-05-11 09:53 UTC, Isidora25 requested changes

2022-05-11 09:53 UTC, Isidora25 commented on src/favorite-movie/favorite-movie.service.ts
> +    return this.favoriteMoviesIdRepository.find({ userId: userId });
Эквивалентно { userId }

2022-05-11 09:53 UTC, Isidora25 commented on src/favorite-movie/favorite-movie.service.ts
> +      movieId: movieId,
{ movieId, userId }

2022-05-11 09:53 UTC, Isidora25 commented on src/movieDB/dto/movieDB.input.ts
> +  @Type(() => String)
А это для чего?

2022-05-11 09:53 UTC, Isidora25 commented on src/movieDB/dto/movieDB.output.ts
> +  posterPath: string;
Кажется, нигде не используется

2022-05-11 09:53 UTC, Isidora25 commented on src/movieDB/dto/movieDB.output.ts
> +  @Field()
Разделяй пробелами поля, пожалуйста, это улучшает читаемость

2022-05-11 09:53 UTC, Isidora25 commented on src/movieDB/dto/movieDB.output.ts
> +  poster_path: string;
Не надо использовать snake_case просто так, тогда у тебя и в схему попадет snake_case 
Чтобы от него избавиться, используй свойство name для Field()

2022-05-11 10:58 UTC, milkyway1170 commented on src/movieDB/dto/movieDB.output.ts
> +  poster_path: string;
А я костылял на фронте... Я прям чуял, что можно филдом поменять)))

2022-05-16 07:31 UTC, Isidora25 requested changes

2022-05-16 07:31 UTC, Isidora25 commented on src/favorite-genre/favorite-genre.service.ts
> +    return await userId;
А что тебе даст в ответе на этот запрос айдишник юзера?
Ты его где-то на фронте используешь? 
Если уж ты хочешь что-то возворащать, то логичнее возвращать айди фильма, юзер у тебя на фронте не меняется, а вот айдишник фильма ты можешь забыть/потерять

2022-05-16 12:21 UTC, Isidora25 approved these changes

2022-05-16 12:57 UTC, merged