Database update
milkyway1170/my_favorite_movies_backend pull request #2
Opened 2022-04-18 08:40 UTC by milkyway1170

2022-04-18 10:00 UTC, reshetov requested changes

2022-04-18 10:00 UTC, reshetov commented on src/services/favorite-genres.service.ts
> +  findAll(): Promise<FavoriteGenre[]> {
А ты точно ничего не перепутал, у тебя файл про Movie работает с Users

2022-04-18 10:00 UTC, reshetov commented on src/services/favorite-movies.service.ts
> +    private usersRepository: Repository<FavoriteMovie>,
И тут тоже, ты или накопировал чего ил я не понимаю

2022-04-18 10:44 UTC, reshetov requested changes

2022-04-18 10:44 UTC, reshetov commented on src/services/favorite-genres.service.ts
> +  findOne(userId: number): Promise<FavoriteGenre> {
Торопишься, у тебя при помощи userId идет поиск жанров, фильмов и т.п.

2022-04-19 06:26 UTC, reshetov approved these changes

2022-04-19 09:27 UTC, Isidora25 requested changes

2022-04-19 09:27 UTC, Isidora25 commented on src/entities/favorite-movie.entity.ts
> +    @PrimaryColumn()
обычно каждая запись в таблице должна иметь свой собственный идентификатор, а не идентификатор юзера или еще чего-то

2022-04-19 09:27 UTC, Isidora25 commented on src/entities/user.entity.ts
> +    userId: number;
идентификатор таблицы обычно называется без указания имени таблицы

2022-04-19 09:27 UTC, Isidora25 commented on src/entities/user.entity.ts
> +    login: string;
Тут желательно добавитть ограничение на уникальность, чтобы в базе не было двух пользователей с одни и тем же логином

2022-04-19 09:27 UTC, Isidora25 commented on src/entities/favorite-movie.entity.ts
> +    movieId: number[];
А для чего здесь массив?

2022-04-19 09:27 UTC, Isidora25 commented on src/services/favorite-genres.service.ts
> +    private genresIdRepository: Repository<FavoriteGenre>,
Это репозиторий, в котом хранятся только айдишники жанров?

2022-04-19 09:27 UTC, Isidora25 commented on src/services/favorite-genres.service.ts
> +  async add(genreListData:IGenreId): Promise<void> {
Проверь форматтер, пробел потерялся после двоеточия

2022-04-19 09:27 UTC, Isidora25 commented on src/services/favorite-movies.service.ts
> +export class MovieService {
Еще один MovieService?

2022-04-19 09:27 UTC, Isidora25 commented on src/services/favorite-movies.service.ts
> +  async add(movieListData:IMovieId): Promise<void> {
пробел

2022-04-19 09:27 UTC, Isidora25 commented on src/services/user.service.ts
> +    user.password = userData.password.trim();
Ну вообще-то пароли нельзя хранить в базе просто так, их нужно хранить в защищенном виде

2022-04-19 09:27 UTC, Isidora25 commented on src/services/user.service.ts
> +    user.userId = userData.userId;
А если юзер уже существует?

2022-04-19 09:27 UTC, Isidora25 commented on src/services/user.service.ts
> +    user.login = userData.login.trim();
Используй деструктуризацию

2022-04-19 13:03 UTC, milkyway1170 commented on src/services/favorite-genres.service.ts
> +    private genresIdRepository: Repository<FavoriteGenre>,
В нем хранятся айдишки, которые были выбраны как любимые. Сейчас подкорректирую название.

2022-04-19 13:45 UTC, milkyway1170 commented on src/services/user.service.ts
> +    user.password = userData.password.trim();
Спрашивал у Андрея на этот счет перед тем, как тебе кидать на проверку, он ответил, что когда придет время - зашифруем)

2022-04-19 14:45 UTC, milkyway1170 commented on src/entities/favorite-movie.entity.ts
> +    movieId: number[];
Каждому пользователю соответствует массив его любимых жанров/фильмов. Плохая практика?
UPD: Все таки ушел от массивов. Теперь в одной записи один айди фильма/жанров.

2022-04-20 09:14 UTC, Isidora25 requested changes

2022-04-20 09:14 UTC, Isidora25 commented on src/migrations/1650017655962-CreateUsers.ts
> +  private newUserTable = new Table({
Разнеси создание каждой из таблиц в отдельную миграцию
Если придется откатить создание одной - откатятся все сразу

2022-04-20 09:14 UTC, Isidora25 commented on src/services/favorite-movies.service.ts
> +  async add({ userId, movieId }: IMovieId): Promise<void> {
а для чего userId, если оно не не сипользуется?

2022-04-20 12:12 UTC, Isidora25 approved these changes

2022-04-21 07:53 UTC, merged