Add graphql
milkyway1170/my_favorite_movies_backend pull request #6
Opened 2022-04-27 10:45 UTC by milkyway1170

2022-04-27 11:21 UTC, Isidora25 requested changes

2022-04-27 11:21 UTC, Isidora25 commented on src/favorite-genre/favorite-genre.resolver.ts
> +  }
спрячь все это в сервис

2022-04-27 11:21 UTC, Isidora25 commented on src/favorite-genre/favorite-genre.resolver.ts
> +    const favoriteGenre = await this.favoriteGenreService.add(
лишняя промежуточная переменная, можно сразу возвращать резльтат из сервиса

2022-04-27 11:21 UTC, Isidora25 commented on src/favorite-movie/favorite-movie.resolver.ts
> +  }
То же самое, убери в сервис

2022-04-27 11:21 UTC, Isidora25 commented on src/favorite-movie/favorite-movie.resolver.ts
> +    return favoriteMovie;
И снова лишняя переменная

2022-04-27 11:21 UTC, Isidora25 commented on src/filter/dto/get-movie-list.input.ts
> +  @Field((type) => [String])
type из  @Fiel можно удалить

2022-04-27 11:21 UTC, Isidora25 commented on src/filter/filter.resolver.ts
> +    return filterData;
лишняя переменная

2022-04-27 11:21 UTC, Isidora25 commented on src/genre/genre.resolver.ts
> +    return genreList;
лишняя переменная

2022-04-27 11:21 UTC, Isidora25 commented on src/movie/movie.resolver.ts
> +    return movieData;
лишняя переменная

2022-04-27 11:21 UTC, Isidora25 commented on src/movie/movie.service.ts
> +    return this.httpService
А если АПИ скажет до-свидания, чего отдадим юзеру?

2022-04-27 11:21 UTC, Isidora25 commented on src/poster/poster.resolver.ts
> +    return path;
Лишняя переменная

2022-04-27 11:21 UTC, Isidora25 commented on src/user/dto/new-user.input.ts
> +  @Length(5, 255)
рекомендую делать подобные проверки на фронте, еще до отправки данных на бэк

2022-04-27 11:21 UTC, Isidora25 commented on src/user/user.resolver.ts
> +    return user;
в сервис

2022-04-27 11:21 UTC, Isidora25 commented on src/user/user.resolver.ts
> +    return user;
в сервис

2022-04-27 11:21 UTC, Isidora25 commented on src/user/user.resolver.ts
> +  }
А ты прям будешь на фронте реализовывать удаление юзера?

2022-04-27 11:21 UTC, Isidora25 commented on src/user/user.service.ts
> +    return this.usersRepository.findOne({ where: { id: userId } });
для findOne `where` не нужен

2022-04-27 11:21 UTC, Isidora25 commented on src/user/user.service.ts
> +    if (typeof isLogin === 'undefined') {
а если null, то пойдет?

2022-04-27 11:21 UTC, Isidora25 commented on src/user/user.service.ts
> +  async add({ login, password }: NewUserInput): Promise<User> {
Что такое add? Это регистрация? Или логин? 
Если логин, то где проверка пароля? 
А как авторизация происходит?

2022-04-28 08:46 UTC, milkyway1170 commented on src/user/user.service.ts
> +  async add({ login, password }: NewUserInput): Promise<User> {
Нейминг поправил. Авторизацию с помощью JWT буду крутить как раз после этого ПР-а.

2022-04-28 08:55 UTC, Isidora25 approved these changes

2022-04-28 09:09 UTC, merged